### ISSUE TITLE
Details in Manually import

### ISSUE THREAD

**Issue by byteyang** [myliang/fish-ui#14]
I thought that the steps of `Manually import` miss some details.

For example, I want to use Button component only, the working steps are:
1. import 'fish-ui/styles/base.less' => import 'fish-ui/__src__/styles/base.less' 
2. Line 1 of button.less: `@import './base.less';` is commented. I need to open it. (It's wired...is there any other consideration?)
3. Vue needs to use this imported Button component by `Vue.component(Button.name, Button)`, which is not mentioned

**Comment by myliang** [comment]
@dreamswhite thanks
