### ISSUE TITLE
Can't resolve './https://fonts.proxy.ustclug.org/css?family=Lato:400,700,400italic,700italic&subset=latin' 

### ISSUE THREAD

**Issue by yoshitaka-motomura** [myliang/fish-ui#18]
Hi I am a bit suffering

`mian.js
import FishUI from 'fish-ui'
Vue.use(FishUI) 
`
When using all the components, when importing as mentioned above, it becomes Cat`t resolve due to the style sheet of external URL of normalize.less line 1 existing in the source

fish-ui/src/styles/normalize.less
`
@import url('https://fonts.proxy.ustclug.org/css?family=Lato:400,700,400italic,700italic&subset=latin');
`

**Comment by Driky** [comment]
I ve got the same problem. I have found that the url give a 404 and even if you find a working one it still does not work. Seems like the less compiler is trying to import the font to inline it.

https://github.com/yeoman/generator-webapp/issues/387 seems to be a similar problem.
