### ISSUE TITLE
How to do an new theme ?

### ISSUE THREAD

**Issue by jmptrader** [myliang/fish-ui#2]
Very cool project. Simple but powerful and elegant.

How to do an new theme ?

You recomend some approach? Or only  I have modify the ** fish-ui/src/styles/ ** files ?

**Comment by myliang** [comment]
@jmptrader  Now it's like this, and it will support the new theme better in the future。
If it's a simple modification, you can modify this file src/styles/base.less

**Comment by jmptrader** [comment]
Thank's.
