### ISSUE TITLE
More detailed example for column cell renderer

### ISSUE THREAD

**Issue by daniellowtw** [myliang/fish-ui#21]
In the example given, it would be greatly helpful if more examples were given for 

```
render: (h, record, column) => h('a', '编辑')}],
```

In particular, what is the type for h? 

An example where an actual hyperlink with URL or different component is rendered would be greatly helpful.

The example was taken from https://myliang.github.io/fish-ui/#/components/table

```
<template>
  <fish-table :columns="columns" :data="data"></fish-table>
</template>
<script>
  export default {
    name: 'demo-table-base',
    data () {
      return {
        columns: [{title: 'Name', key: 'name'},
          {title: 'age', key: 'age'},
          {title: 'Address', key: 'address'},
          {title: 'Operate',
            key: 'operate',
            render: (h, record, column) => h('a', '编辑')}],
        data: [
          {name: 'yanbin.hu', age: 32, address: 'haidi part 1, xihu, Hangzhou'},
          {name: 'yanzu.wu', age: 35, address: 'haidi part 5, xihu, Hangzhou'},
          {name: 'yanzu.wu', age: 35, address: 'haidi part 5, xihu, Hangzhou'},
          {name: 'yanzu.wu', age: 35, address: 'haidi part 5, xihu, Hangzhou'}
        ]
      }
    }
  }
</script>
```

**Comment by myliang** [comment]
@daniellowtw 
h = createElement
https://cn.vuejs.org/v2/guide/render-function.html#JSX

**Comment by daniellowtw** [comment]
Yes, I eventually found that page after digging into how it is implemented and a bit of searching on vue's documentation. For a novice user like myself, it was a struggle trying to pass the record down to a child vue component for rendering and I felt that more examples would have been useful.
