### ISSUE TITLE
Fish UI localization - config locale for moment.js

### ISSUE THREAD

**Issue by Deprime** [myliang/fish-ui#32]
Is there any way to set default config for moment.js like **moment.locale('fr');** ?

**Comment by myliang** [comment]
?

**Comment by Deprime** [comment]
I'm using Fish UI in my project and often use **Datepicker** component. So by default it has english language.  But my project for Russian users. 
In **Readme.md** I find it out, that Fish UI using **Moment.js** for date-time objects.
So my question is: how can i configurate Datepicker component to localize it in russian language?

**Comment by myliang** [comment]
not support localization, but you can git clone and modify https://github.com/myliang/fish-ui/blob/master/src/config.js

**Comment by myliang** [comment]
update to fish-ui@1.1.72 
![image](https://user-images.githubusercontent.com/718858/59595432-5c9ca580-9128-11e9-887a-d1ce5319407b.png)

**Comment by Deprime** [comment]
Ok. Thanks for the guidance

**Comment by myliang** [comment]
feedback if there is any problem

**Comment by Deprime** [comment]
Week and month attributes for Datepicker is good decision, but, for example, I need to set the first day of the week - Monday. This is the last trouble for me now )) So it seems that I will still need to change the calendar configuration file.

**Comment by myliang** [comment]
> Week and month attributes for Datepicker is good decision, but, for example, I need to set the first day of the week - Monday. This is the last trouble for me now )) So it seems that I will still need to change the calendar configuration file.

@Deprime update to fish-ui@1.1.73
