### ISSUE TITLE
不显示icon

### ISSUE THREAD

**Issue by bay1ts** [myliang/fish-ui#33]
侧导航,分页等不显示icon.只显示一个方框.
请问需要install 其他依赖吗?

**Comment by myliang** [comment]
```html
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.proxy.ustclug.org/css?family=Lato:400,700,400italic,700italic&subset=latin"/>

```

**Comment by renzified** [comment]
> ```
>     <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
>     <link rel="stylesheet" href="https://fonts.proxy.ustclug.org/css?family=Lato:400,700,400italic,700italic&subset=latin"/>
> ```

how can i use this inside a menu items along with the content text
