### ISSUE TITLE
Modal margin-top option

### ISSUE THREAD

**Issue by Deprime** [myliang/fish-ui#34]
Hello. Option for **margin-top**  in the modal window  cmponent will be very useful.
Something like:
`<fish-modal :top="5%">`
or
`<fish-modal :top="20px">`

**Comment by myliang** [comment]
![image](https://user-images.githubusercontent.com/718858/64025054-6a31cb00-cb6e-11e9-9e26-9dd7be936887.png)

**Comment by Deprime** [comment]
Ups. I didn't see it in the documentation. My apologies
