### ISSUE TITLE
const install = function (Vue, opts = {}) {}  occur a error

### ISSUE THREAD

**Issue by niloay** [myliang/fish-ui#4]
Uncaught TypeError: Object.values is not a function

**Comment by myliang** [comment]
what? Vue version? Node version?

**Comment by myliang** [comment]
@jAVA-yaolin ?

**Comment by myliang** [comment]
@jAVA-yaolin brower version

**Comment by moker-monkey** [comment]
我也遇到这个问题了，用了你的脚手架，并且npm install fish-ui ，然后引入就报这个错

**Comment by myliang** [comment]
@moker-monkey 你本地的node版本升级一下， npm install --save-dev less less-loader fish-ui

**Comment by niloay** [comment]
update node
