### ISSUE TITLE
Cascader icon bad alignment

### ISSUE THREAD

**Issue by amiceli** [myliang/fish-ui#7]
On demo website, cascader arrow icons arn't correctly aligned : 

<img width="577" alt="image" src="https://user-images.githubusercontent.com/5556115/33709552-fad14fb4-db3d-11e7-8087-a2355a4312d4.png">

EDIT : it happens on firefox, not with chrome

EDIT : check my pull request https://github.com/myliang/fish-ui/pull/8

**Comment by myliang** [comment]
@amiceli fixed this bug
